name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0
    - name: Install dependencies
      run: dotnet restore
    - name: Build Solution
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish API
      run: dotnet publish ".\AmerFamilyPlayoffs.Api\AmerFamilyPlayoffs.Api.csproj" -c Release -o publishApi --self-contained true -r win-x86
    - name: Publish WASM
      run: dotnet publish ".\BlazorWasm\AmerFamilyPlayoffs.csproj" -c Release -o publishWasm
    - name: FTP Deploy API
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publishApi/
        server-dir: httpdocs/
    - name: FTP Deploy WASM
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publishWasm/
        server-dir: core.stevencodeswright.com/
